"""Removed Shop and redefined Product's relationship with User

Revision ID: b3384b2132bd
Revises: a277aba88f7c
Create Date: 2025-03-26 14:16:43.067337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3384b2132bd'
down_revision = 'a277aba88f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('catid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('catid')
    )
    op.create_table('cart',
    sa.Column('carid', sa.String(length=64), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('carid')
    )
    op.create_table('order',
    sa.Column('orderid', sa.String(length=64), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('sellerid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'shipped', 'delivered'), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sellerid'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('orderid')
    )
    op.create_table('product',
    sa.Column('proid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('catid', sa.String(length=64), nullable=True),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catid'], ['category.catid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('proid')
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carid', sa.String(length=64), nullable=True),
    sa.Column('proid', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carid'], ['cart.carid'], ),
    sa.ForeignKeyConstraint(['proid'], ['product.proid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.String(length=64), nullable=True),
    sa.Column('proid', sa.String(length=64), nullable=True),
    sa.Column('productname', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orderid'], ['order.orderid'], ),
    sa.ForeignKeyConstraint(['proid'], ['product.proid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('shopid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('userid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('shopname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('shopdesc', mysql.TEXT(), nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], name='shop_ibfk_1'),
    sa.PrimaryKeyConstraint('shopid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orderitem')
    op.drop_table('cartitem')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('category')
    # ### end Alembic commands ###
