"""Initial

Revision ID: cf8983b2aea0
Revises: 
Create Date: 2025-03-22 11:15:32.342873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8983b2aea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('catid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('catid')
    )
    op.create_table('user',
    sa.Column('userid', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('buyer', 'seller', 'admin'), nullable=False),
    sa.Column('shipping_address', sa.String(length=200), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('cart',
    sa.Column('carid', sa.String(length=64), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('carid')
    )
    op.create_table('product',
    sa.Column('proid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('catid', sa.String(length=64), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catid'], ['category.catid'], ),
    sa.PrimaryKeyConstraint('proid')
    )
    op.create_table('shop',
    sa.Column('shopid', sa.String(length=64), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('shopname', sa.String(length=100), nullable=False),
    sa.Column('shopdesc', sa.Text(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('shopid')
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carid', sa.String(length=64), nullable=True),
    sa.Column('proid', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carid'], ['cart.carid'], ),
    sa.ForeignKeyConstraint(['proid'], ['product.proid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('orderid', sa.String(length=64), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('shopid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'shipped', 'delivered'), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shopid'], ['shop.shopid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('orderid')
    )
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.String(length=64), nullable=True),
    sa.Column('proid', sa.String(length=64), nullable=True),
    sa.Column('productname', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orderid'], ['order.orderid'], ),
    sa.ForeignKeyConstraint(['proid'], ['product.proid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.drop_table('order')
    op.drop_table('cartitem')
    op.drop_table('shop')
    op.drop_table('product')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
